# Project config
server:
  servlet:
    context-path: /gmblog-adm
  port: 9100
  address: 127.0.0.1

# Druid config
spring:
  application:
    name: gm-blog-adm-service
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/gk_gm_blog?characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: killer1992ok!
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 10
      max-active: 10
      max-wait: 60000
      validation-query: select CURRENT_DATE FROM dual
      validation-query-timeout: 60000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 600000
      filters: stat
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456

# Logging config
logging:
  file:
    path: /Users/geekchief/Desktop/Work/Workspace/Geekkampong/2cl/gm-blog-adm-service/
    name: log.log
  level:
    root: info

# Eureka config
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:9006/gmblog-rc/eureka/
